package com.nukkitx.network.util;

public enum DisconnectReason {
   CLOSED_BY_REMOTE_PEER,
   SHUTTING_DOWN,
   DISCONNECTED,
   TIMED_OUT,
   CONNECTION_REQUEST_FAILED,
   ALREADY_CONNECTED,
   NO_FREE_INCOMING_CONNECTIONS,
   INCOMPATIBLE_PROTOCOL_VERSION,
   IP_RECENTLY_CONNECTED,
   BAD_PACKET;

   // $FF: synthetic method
   private static DisconnectReason[] $values() {
      return new DisconnectReason[]{CLOSED_BY_REMOTE_PEER, SHUTTING_DOWN, DISCONNECTED, TIMED_OUT, CONNECTION_REQUEST_FAILED, ALREADY_CONNECTED, NO_FREE_INCOMING_CONNECTIONS, INCOMPATIBLE_PROTOCOL_VERSION, IP_RECENTLY_CONNECTED, BAD_PACKET};
   }
}
