package com.nukkitx.protocol.bedrock.codec.v388;

import com.nukkitx.protocol.bedrock.codec.BedrockCodec;
import com.nukkitx.protocol.bedrock.codec.EntityDataTypeMap;
import com.nukkitx.protocol.bedrock.codec.v291.serializer.EntityEventSerializer_v291;
import com.nukkitx.protocol.bedrock.codec.v291.serializer.LevelEventSerializer_v291;
import com.nukkitx.protocol.bedrock.codec.v291.serializer.LevelSoundEvent1Serializer_v291;
import com.nukkitx.protocol.bedrock.codec.v313.serializer.LevelSoundEvent2Serializer_v313;
import com.nukkitx.protocol.bedrock.codec.v332.serializer.LevelSoundEventSerializer_v332;
import com.nukkitx.protocol.bedrock.codec.v361.Bedrock_v361;
import com.nukkitx.protocol.bedrock.codec.v361.serializer.LevelEventGenericSerializer_v361;
import com.nukkitx.protocol.bedrock.codec.v361.serializer.ResourcePackDataInfoSerializer_v361;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.AddPlayerSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.AnvilDamageSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.AvailableCommandsSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.CompletedUsingItemSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.CraftingDataSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.EducationSettingsSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.EmoteSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.EventSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.InteractSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.MoveEntityDeltaSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.MultiplayerSettingsSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.NetworkSettingsSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.PlayerAuthInputSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.PlayerListSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.PlayerSkinSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.ResourcePackChunkDataSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.ResourcePackStackSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.RespawnSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.SettingsCommandSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.StartGameSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.StructureBlockUpdateSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.StructureTemplateDataResponseSerializer_v388;
import com.nukkitx.protocol.bedrock.codec.v388.serializer.TickSyncSerializer_v388;
import com.nukkitx.protocol.bedrock.data.LevelEvent;
import com.nukkitx.protocol.bedrock.data.LevelEventType;
import com.nukkitx.protocol.bedrock.data.PacketRecipient;
import com.nukkitx.protocol.bedrock.data.ResourcePackType;
import com.nukkitx.protocol.bedrock.data.SoundEvent;
import com.nukkitx.protocol.bedrock.data.command.CommandParam;
import com.nukkitx.protocol.bedrock.data.entity.EntityDataFormat;
import com.nukkitx.protocol.bedrock.data.entity.EntityDataTypes;
import com.nukkitx.protocol.bedrock.data.entity.EntityEventType;
import com.nukkitx.protocol.bedrock.data.entity.EntityFlag;
import com.nukkitx.protocol.bedrock.packet.AddPlayerPacket;
import com.nukkitx.protocol.bedrock.packet.AnvilDamagePacket;
import com.nukkitx.protocol.bedrock.packet.AvailableCommandsPacket;
import com.nukkitx.protocol.bedrock.packet.CompletedUsingItemPacket;
import com.nukkitx.protocol.bedrock.packet.CraftingDataPacket;
import com.nukkitx.protocol.bedrock.packet.EducationSettingsPacket;
import com.nukkitx.protocol.bedrock.packet.EmotePacket;
import com.nukkitx.protocol.bedrock.packet.EntityEventPacket;
import com.nukkitx.protocol.bedrock.packet.EventPacket;
import com.nukkitx.protocol.bedrock.packet.ExplodePacket;
import com.nukkitx.protocol.bedrock.packet.InteractPacket;
import com.nukkitx.protocol.bedrock.packet.LevelEventGenericPacket;
import com.nukkitx.protocol.bedrock.packet.LevelEventPacket;
import com.nukkitx.protocol.bedrock.packet.LevelSoundEvent1Packet;
import com.nukkitx.protocol.bedrock.packet.LevelSoundEvent2Packet;
import com.nukkitx.protocol.bedrock.packet.LevelSoundEventPacket;
import com.nukkitx.protocol.bedrock.packet.MoveEntityDeltaPacket;
import com.nukkitx.protocol.bedrock.packet.MultiplayerSettingsPacket;
import com.nukkitx.protocol.bedrock.packet.NetworkSettingsPacket;
import com.nukkitx.protocol.bedrock.packet.PlayerAuthInputPacket;
import com.nukkitx.protocol.bedrock.packet.PlayerListPacket;
import com.nukkitx.protocol.bedrock.packet.PlayerSkinPacket;
import com.nukkitx.protocol.bedrock.packet.ResourcePackChunkDataPacket;
import com.nukkitx.protocol.bedrock.packet.ResourcePackDataInfoPacket;
import com.nukkitx.protocol.bedrock.packet.ResourcePackStackPacket;
import com.nukkitx.protocol.bedrock.packet.RespawnPacket;
import com.nukkitx.protocol.bedrock.packet.SettingsCommandPacket;
import com.nukkitx.protocol.bedrock.packet.StartGamePacket;
import com.nukkitx.protocol.bedrock.packet.StructureBlockUpdatePacket;
import com.nukkitx.protocol.bedrock.packet.StructureTemplateDataResponsePacket;
import com.nukkitx.protocol.bedrock.packet.TickSyncPacket;
import com.nukkitx.protocol.bedrock.transformer.BooleanTransformer;
import com.nukkitx.protocol.bedrock.transformer.FlagTransformer;
import com.nukkitx.protocol.bedrock.transformer.TypeMapTransformer;
import com.nukkitx.protocol.common.util.TypeMap;

public class Bedrock_v388 extends Bedrock_v361 {
   protected static final TypeMap<EntityFlag> ENTITY_FLAGS;
   protected static final EntityDataTypeMap ENTITY_DATA;
   protected static final TypeMap<CommandParam> COMMAND_PARAMS;
   protected static final TypeMap<EntityEventType> ENTITY_EVENTS;
   protected static final TypeMap<LevelEventType> LEVEL_EVENTS;
   protected static final TypeMap<SoundEvent> SOUND_EVENTS;
   protected static final TypeMap<ResourcePackType> RESOURCE_PACK_TYPES;
   public static final BedrockCodec CODEC;

   static {
      ENTITY_FLAGS = Bedrock_v361.ENTITY_FLAGS.toBuilder().insert(88, EntityFlag.IS_IN_UI).insert(89, EntityFlag.STALKING).insert(90, EntityFlag.EMOTING).insert(91, EntityFlag.CELEBRATING).build();
      ENTITY_DATA = Bedrock_v361.ENTITY_DATA.toBuilder().update(EntityDataTypes.FLAGS, new FlagTransformer(ENTITY_FLAGS, 0)).update(EntityDataTypes.FLAGS_2, new FlagTransformer(ENTITY_FLAGS, 1)).update(EntityDataTypes.AREA_EFFECT_CLOUD_PARTICLE, new TypeMapTransformer(PARTICLE_TYPES)).insert(EntityDataTypes.AMBIENT_SOUND_INTERVAL, 107, EntityDataFormat.FLOAT).insert(EntityDataTypes.AMBIENT_SOUND_INTERVAL_RANGE, 108, EntityDataFormat.FLOAT).insert(EntityDataTypes.AMBIENT_SOUND_EVENT_NAME, 109, EntityDataFormat.STRING).insert(EntityDataTypes.FALL_DAMAGE_MULTIPLIER, 110, EntityDataFormat.FLOAT).insert(EntityDataTypes.NAME_RAW_TEXT, 111, EntityDataFormat.STRING).insert(EntityDataTypes.CAN_RIDE_TARGET, 112, EntityDataFormat.BYTE, BooleanTransformer.INSTANCE).build();
      COMMAND_PARAMS = Bedrock_v361.COMMAND_PARAMS.toBuilder().shift(27, 2).shift(31, 7).insert(37, CommandParam.BLOCK_POSITION).shift(46, 1).build();
      ENTITY_EVENTS = Bedrock_v361.ENTITY_EVENTS.toBuilder().insert(74, EntityEventType.FINISHED_CHARGING_ITEM).build();
      LEVEL_EVENTS = Bedrock_v361.LEVEL_EVENTS.toBuilder().insert(2024, LevelEvent.PARTICLE_POINT_CLOUD).insert(2025, LevelEvent.PARTICLE_EXPLOSION).insert(2026, LevelEvent.PARTICLE_BLOCK_EXPLOSION).build();
      SOUND_EVENTS = Bedrock_v361.SOUND_EVENTS.toBuilder().replace(274, SoundEvent.AMBIENT_IN_RAID).insert(275, SoundEvent.UI_CARTOGRAPHY_TABLE_USE).insert(276, SoundEvent.UI_STONECUTTER_USE).insert(277, SoundEvent.UI_LOOM_USE).insert(278, SoundEvent.SMOKER_USE).insert(279, SoundEvent.BLAST_FURNACE_USE).insert(280, SoundEvent.SMITHING_TABLE_USE).insert(281, SoundEvent.SCREECH).insert(282, SoundEvent.SLEEP).insert(283, SoundEvent.FURNACE_USE).insert(284, SoundEvent.MOOSHROOM_CONVERT).insert(285, SoundEvent.MILK_SUSPICIOUSLY).insert(286, SoundEvent.CELEBRATE).insert(287, SoundEvent.UNDEFINED).build();
      RESOURCE_PACK_TYPES = Bedrock_v361.RESOURCE_PACK_TYPES.toBuilder().replace(1, ResourcePackType.ADDON).replace(2, ResourcePackType.CACHED).replace(3, ResourcePackType.COPY_PROTECTED).replace(4, ResourcePackType.DATA_ADD_ON).replace(5, ResourcePackType.PERSONA_PIECE).replace(6, ResourcePackType.RESOURCES).replace(7, ResourcePackType.SKINS).insert(8, ResourcePackType.WORLD_TEMPLATE).build();
      CODEC = Bedrock_v361.CODEC.toBuilder().protocolVersion(388).minecraftVersion("1.13.0").helper(() -> new BedrockCodecHelper_v388(ENTITY_DATA, GAME_RULE_TYPES)).deregisterPacket(ExplodePacket.class).updateSerializer(ResourcePackDataInfoPacket.class, new ResourcePackDataInfoSerializer_v361(RESOURCE_PACK_TYPES)).updateSerializer(ResourcePackStackPacket.class, ResourcePackStackSerializer_v388.INSTANCE).updateSerializer(StartGamePacket.class, StartGameSerializer_v388.INSTANCE).updateSerializer(AddPlayerPacket.class, AddPlayerSerializer_v388.INSTANCE).updateSerializer(InteractPacket.class, InteractSerializer_v388.INSTANCE).updateSerializer(RespawnPacket.class, RespawnSerializer_v388.INSTANCE).updateSerializer(CraftingDataPacket.class, CraftingDataSerializer_v388.INSTANCE).updateSerializer(PlayerListPacket.class, PlayerListSerializer_v388.INSTANCE).updateSerializer(EventPacket.class, EventSerializer_v388.INSTANCE).updateSerializer(AvailableCommandsPacket.class, new AvailableCommandsSerializer_v388(COMMAND_PARAMS)).updateSerializer(ResourcePackChunkDataPacket.class, ResourcePackChunkDataSerializer_v388.INSTANCE).updateSerializer(StructureBlockUpdatePacket.class, StructureBlockUpdateSerializer_v388.INSTANCE).updateSerializer(PlayerSkinPacket.class, PlayerSkinSerializer_v388.INSTANCE).updateSerializer(MoveEntityDeltaPacket.class, MoveEntityDeltaSerializer_v388.INSTANCE).updateSerializer(StructureTemplateDataResponsePacket.class, StructureTemplateDataResponseSerializer_v388.INSTANCE).updateSerializer(EntityEventPacket.class, new EntityEventSerializer_v291(ENTITY_EVENTS)).updateSerializer(LevelSoundEvent1Packet.class, new LevelSoundEvent1Serializer_v291(SOUND_EVENTS)).updateSerializer(LevelSoundEvent2Packet.class, new LevelSoundEvent2Serializer_v313(SOUND_EVENTS)).updateSerializer(LevelSoundEventPacket.class, new LevelSoundEventSerializer_v332(SOUND_EVENTS)).updateSerializer(LevelEventPacket.class, new LevelEventSerializer_v291(LEVEL_EVENTS)).updateSerializer(LevelEventGenericPacket.class, new LevelEventGenericSerializer_v361(LEVEL_EVENTS)).registerPacket(TickSyncPacket::new, TickSyncSerializer_v388.INSTANCE, 23, PacketRecipient.BOTH).registerPacket(EducationSettingsPacket::new, EducationSettingsSerializer_v388.INSTANCE, 137, PacketRecipient.CLIENT).registerPacket(EmotePacket::new, EmoteSerializer_v388.INSTANCE, 138, PacketRecipient.BOTH).registerPacket(MultiplayerSettingsPacket::new, MultiplayerSettingsSerializer_v388.INSTANCE, 139, PacketRecipient.BOTH).registerPacket(SettingsCommandPacket::new, SettingsCommandSerializer_v388.INSTANCE, 140, PacketRecipient.SERVER).registerPacket(AnvilDamagePacket::new, AnvilDamageSerializer_v388.INSTANCE, 141, PacketRecipient.SERVER).registerPacket(CompletedUsingItemPacket::new, CompletedUsingItemSerializer_v388.INSTANCE, 142, PacketRecipient.CLIENT).registerPacket(NetworkSettingsPacket::new, NetworkSettingsSerializer_v388.INSTANCE, 143, PacketRecipient.CLIENT).registerPacket(PlayerAuthInputPacket::new, PlayerAuthInputSerializer_v388.INSTANCE, 144, PacketRecipient.SERVER).build();
   }
}
